services:
  - type: web
    name: sentiment-analysis-backend
    env: python
    region: oregon
    plan: free
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install --no-cache-dir -r backend/requirements.txt
    startCommand: cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: MODEL_PATH
        value: ../model
      - key: ENVIRONMENT
        value: production
      - key: FRONTEND_URL
        value: https://your-frontend-url.vercel.app
    autoDeploy: false
