services:
  - type: web
    name: sentiment-analysis-backend
    runtime: docker
    plan: free
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: TRANSFORMERS_CACHE
        value: /tmp/transformers_cache
      - key: HF_HOME
        value: /tmp/huggingface
      - key: PYTORCH_TRANSFORMERS_CACHE
        value: /tmp/transformers_cache
      - key: PORT
        value: 8000
    healthCheckPath: /health
    autoDeploy: true
